algoritmo "operadores_relacionais_portugol"
// tipos de operadores:
// > Maior que
// < Menor que
// >= Maior ou igual a
// <= Menor ou igual a
// = Igual a
// <> Diferente de

var
        a, b, c, d: inteiro
inicio
      a <- 2
      b <- 3
      c <- 5
      d <- 5
      escreval (a=b)
      escreval (a>b)
      escreval (a<>c)
      escreval (c<=d)
      escreval (a+b+c)
      escreval (a + (b*c)/2)



fimalgoritmo
